<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class productSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('product')->insert([
            // 8 for Men's Clothing
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Reflection 073',
                'product_name' => 'Puma Fuse',
                'product_price' => 79.00,
                'image' => '/images/m1.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Grey-Cosmic',
                'product_name' => 'Puma Flex 2.0',
                'product_price' => 88.00,
                'image' => '/images/m2.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Silver-Mint',
                'product_name' => 'Puma Flex',
                'product_price' => 59.00,
                'image' => '/images/m3.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Sea Salt 108',
                'product_name' => 'Neo Short',
                'product_price' => 69.00,
                'image' => '/images/m4.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'White-In-Blue',
                'product_name' => 'Kappa Breakable',
                'product_price' => 50.00,
                'image' => '/images/m5.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Black-Dk-Grey',
                'product_name' => 'Nike Nba Swingman',
                'product_price' => 89.00,
                'image' => '/images/m6.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Multi-Colour',
                'product_name' => 'Market HUF',
                'product_price' => 99.00,
                'image' => '/images/m7.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Clothes',
                'product_description' => 'Chill-Blue',
                'product_name' => 'Market Graphic',
                'product_price' => 99.00,
                'image' => '/images/m8.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            // 8 for Women's Clothing
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'IVY Park',
                'product_price' => 79.00,
                'image' => '/images/w1.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Nike Suit',
                'product_price' => 158.00,
                'image' => '/images/w2.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Under Armour Soften',
                'product_price' => 89.00,
                'image' => '/images/w3.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Vogue Flora',
                'product_price' => 69.00,
                'image' => '/images/w4.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Kappa Style',
                'product_price' => 50.00,
                'image' => '/images/w5.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Abibas Branded',
                'product_price' => 89.00,
                'image' => '/images/w6.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Relax Abibas',
                'product_price' => 79.00,
                'image' => '/images/w7.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Clothes',
                'product_description' => '',
                'product_name' => 'Abibas Fusion',
                'product_price' => 129.00,
                'image' => '/images/w8.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            // 8 for Men's Shoes
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Reflection 073',
                'product_name' => 'New Balance 574',
                'product_price' => 379.00,
                'image' => '/images/1.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Grey-Cosmic',
                'product_name' => 'Nike E-Series',
                'product_price' => 488.00,
                'image' => '/images/2.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Silver-Mint',
                'product_name' => 'Nike Dunk Low',
                'product_price' => 539.00,
                'image' => '/images/3.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Sea Salt 108',
                'product_name' => 'New Balance Neo',
                'product_price' => 699.00,
                'image' => '/images/4.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'White-In-Blue',
                'product_name' => 'Nike Air Force 3',
                'product_price' => 450.00,
                'image' => '/images/5.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Black-Dk-Grey',
                'product_name' => 'Nike Air Trainer',
                'product_price' => 589.00,
                'image' => '/images/6.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Multi-Colour',
                'product_name' => 'Nike Lebron XX',
                'product_price' => 919.00,
                'image' => '/images/7.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Men',
                'product_category' => 'Footwear',
                'product_description' => 'Nike Dunk Higg',
                'product_name' => 'Chill-Blue',
                'product_price' => 425.00,
                'image' => '/images/8.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            // 8 for Women's Shoes 
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Bounce 2',
                'product_name' => 'Nike Go',
                'product_price' => 479.00,
                'image' => '/images/9.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Grey-Cosmic',
                'product_name' => 'New Balance 9004',
                'product_price' => 548.00,
                'image' => '/images/10.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Purple-Mint',
                'product_name' => 'Air Jordan 1',
                'product_price' => 639.00,
                'image' => '/images/11.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Purple-bleach',
                'product_name' => 'Nike Air Force 2',
                'product_price' => 499.00,
                'image' => '/images/12.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Black-In-White',
                'product_name' => 'Converse HighEnd',
                'product_price' => 550.00,
                'image' => '/images/13.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Slipper',
                'product_name' => 'New Balance Freedom',
                'product_price' => 189.00,
                'image' => '/images/14.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Pure-White',
                'product_name' => 'Abibas Hipperboost',
                'product_price' => 919.00,
                'image' => '/images/15.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ],
            [
                'product_type' => 'Women',
                'product_category' => 'Footwear',
                'product_description' => 'Multiverse',
                'product_name' => 'Puma Multiver',
                'product_price' => 745.00,
                'image' => '/images/16.png', 
                'created_at' => '2023-03-21',
                'updated_at' => '2023-03-21',
            ]
        ]);
    }
}
